#!/usr/bin/env bash
# Setting haproxy as load balancer
sudo apt-get update
sudo apt-get -y install haproxy
printf "\nfrontend hbtn-lb\n
\tbind *:80\n
\tmode http\n
\toption forwardfor\n
\tdefault_backend servers\n\n
backend servers\n\
\tbalance roundrobin\n
\tserver web-01 34.74.57.2:80\n
\tserver web-02 52.90.165.93:80\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
