#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times (while) 
# but with 3 stages (4th, 9th, 17th) iteration

i=1
while [ $i -le 20 ]
do
	echo $i
	
	case $i in 
		4)
			echo "bad luck from China"
			;;
		
		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;
	esac

	: $(( i++ ))
done
