#!/usr/bin/env bash
# This script is displaying information about the holbertonschool file 

filename="holbertonschool"
if [ ! -e $filename ]
then
	echo "holbertonschool file does not exist"
	exit 0
fi

echo "holbertonschool file exists"

if [ -s $filename ]
then
	echo "holbertonschool file is not empty"
else
	echo "holbertonschool file is empty"
fi

if [ ! -d $filename ]
then
	echo "holbertonschool is a regular file"
fi
